/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Alumno
 */
public class Administracion extends javax.swing.JFrame {
    Funciones.Usuarios usuarios = new Funciones.Usuarios();
    Funciones.Productos aProd = new Funciones.Productos();
    Funciones.Tablas tablas = new Funciones.Tablas();
    DefaultTableModel model;
    Login login = new Login();
    public static boolean insertMode, filtrado=false;
    public static int idProd;
    TableRowSorter filtro;
    int fila;
    
    //Variables para Realizar los procedimientos:
    float precioCompra, precioVenta, ganancia;
    
    public Administracion() throws SQLException{
        initComponents();
        this.setLocationRelativeTo(null);
        model = (DefaultTableModel) this.tablaProd.getModel();
        tablaProd.setModel(tablas.adminTablaProductos(model, ""));
        gRBSolicita.add(rbBo_Lo); gRBSolicita.add(rbPro_Bo);
        btnProdSolicita.setText("Solicitudes Pendientes("+aProd.getSoliCant()+")");
        tablaProd.clearSelection();
        tablaProd.getColumnModel().getColumn(0).setMaxWidth(50);
        tablaProd.getColumnModel().getColumn(8).setMaxWidth(80);
        tablaProd.getColumnModel().getColumn(7).setMaxWidth(80);
        tablaProd.getColumnModel().getColumn(6).setMaxWidth(80);
        tablaProd.getColumnModel().getColumn(5).setMaxWidth(80);
        tablaProd.getColumnModel().getColumn(4).setMaxWidth(80);
        tablaProd.getColumnModel().getColumn(2).setMaxWidth(80);
        tablaProd.setDefaultRenderer(Object.class, new Render());
        this.setIconImage(new ImageIcon(getClass().getResource("../Imagenes/iconos/logo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gRBSolicita = new javax.swing.ButtonGroup();
        frameSolicitaProd = new javax.swing.JFrame();
        btnSoliProd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSelectProv = new javax.swing.JTable();
        btnCancelProvSoli = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tf_preCompra = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        tfFindProd = new javax.swing.JTextField();
        btnProdSolicita = new javax.swing.JButton();
        btnAddProd = new javax.swing.JButton();
        btnModProd = new javax.swing.JButton();
        btnDelProd = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rbBo_Lo = new javax.swing.JRadioButton();
        rbPro_Bo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        spinCantSolicita = new javax.swing.JSpinner();
        btnSolicitarProd = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        btnFindProd = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        optLogOut = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        optUsuarios = new javax.swing.JMenuItem();
        optProveedores = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        btnSoliProd.setText("Solicitar");
        btnSoliProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoliProdActionPerformed(evt);
            }
        });

        tblSelectProv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Codigo", "Proveedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSelectProv);

        btnCancelProvSoli.setText("Cancelar");
        btnCancelProvSoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelProvSoliActionPerformed(evt);
            }
        });

        jLabel3.setText("Precio de Compra:");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(3);
        jTextArea1.setText("*El Precio de Compra ha sido seleccionado automáticamente.\n si el precio de compra a este proveedor es diferente, \npuede ajustar al precio correcto");
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout frameSolicitaProdLayout = new javax.swing.GroupLayout(frameSolicitaProd.getContentPane());
        frameSolicitaProd.getContentPane().setLayout(frameSolicitaProdLayout);
        frameSolicitaProdLayout.setHorizontalGroup(
            frameSolicitaProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameSolicitaProdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameSolicitaProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameSolicitaProdLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(frameSolicitaProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCancelProvSoli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSoliProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(frameSolicitaProdLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_preCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(frameSolicitaProdLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frameSolicitaProdLayout.setVerticalGroup(
            frameSolicitaProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameSolicitaProdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameSolicitaProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_preCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(frameSolicitaProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameSolicitaProdLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnSoliProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelProvSoli))
                    .addGroup(frameSolicitaProdLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel de Administracion");

        tablaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Marca", "Proveedor", "Precio Compra", "Precio C/U", "Precio por Paquete", "Local Stock", "Bodega Stock", "minRepo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaProd);

        jLabel2.setText("Buscar");

        tfFindProd.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfFindProdCaretUpdate(evt);
            }
        });
        tfFindProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfFindProdKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfFindProdKeyPressed(evt);
            }
        });

        btnProdSolicita.setText("Solicitudes Pendientes()");
        btnProdSolicita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdSolicitaActionPerformed(evt);
            }
        });

        btnAddProd.setText("Añadir Producto");
        btnAddProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdActionPerformed(evt);
            }
        });

        btnModProd.setText("Actualizar Producto");
        btnModProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModProdActionPerformed(evt);
            }
        });

        btnDelProd.setText("Remover Producto");
        btnDelProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelProdActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Solicitar Más Productos"));

        rbBo_Lo.setSelected(true);
        rbBo_Lo.setText("De Bodega a Local");

        rbPro_Bo.setText("De Proveedor A Bodega");

        jLabel1.setText("Cantidad:");

        spinCantSolicita.setValue(0);

        btnSolicitarProd.setText("Solicitar");
        btnSolicitarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbBo_Lo)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spinCantSolicita, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbPro_Bo)
                        .addGap(50, 50, 50)
                        .addComponent(btnSolicitarProd)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbBo_Lo)
                    .addComponent(jLabel1)
                    .addComponent(spinCantSolicita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbPro_Bo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnSolicitarProd)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ventas y Usuarios"));

        jButton12.setText("Usuarios");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Estadisticas");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton13)
                .addContainerGap())
        );

        btnFindProd.setText("Buscar");
        btnFindProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindProdActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/update.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        optLogOut.setText("Cerrar Sesión");
        optLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optLogOutActionPerformed(evt);
            }
        });
        jMenu1.add(optLogOut);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Administrar");

        jMenuItem4.setText("Compras y Ventas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        optUsuarios.setText("Usuarios");
        optUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optUsuariosActionPerformed(evt);
            }
        });
        jMenu2.add(optUsuarios);

        optProveedores.setText("Proveedores");
        optProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optProveedoresActionPerformed(evt);
            }
        });
        jMenu2.add(optProveedores);

        jMenuItem1.setText("Marcas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(169, 169, 169)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnDelProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnModProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAddProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfFindProd, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFindProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnProdSolicita)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(tfFindProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnProdSolicita)
                        .addComponent(btnFindProd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelProd))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc="Metodos para la solicitud de productos">
    
    private void btnSolicitarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarProdActionPerformed
      
        model = (DefaultTableModel) tablaProd.getModel();
        fila = tablaProd.getSelectedRow();
        //Obtener el ID de Producto.
        if(fila>=0){
            
            aProd.setCodigo(Integer.valueOf(model.getValueAt(fila, 0).toString()));
            
            
            if(Integer.valueOf(spinCantSolicita.getValue().toString()) < 1){
                JOptionPane.showMessageDialog(this, "Aún no ha especificado una cantidad a solitar");
            }else{
                
                int bodeCant = Integer.parseInt(model.getValueAt(fila, 8).toString());
        int cant = Integer.parseInt(spinCantSolicita.getValue().toString());

        String marca = model.getValueAt(fila, 2).toString();
        String provs = model.getValueAt(fila, 3).toString();

        if(rbBo_Lo.isSelected()){
            if(cant<=bodeCant){
                try {
                    aProd.selectProd();
                    if(aProd.solicitarProd("Bodega", "Local", cant, marca, provs, null)){
                        JOptionPane.showMessageDialog(this, "Añadido a Solicitudes Pendientes.");
                        tablaProd.clearSelection();
                        spinCantSolicita.setValue(0);
                    }else{
                        JOptionPane.showMessageDialog(this, "No se Pudo Añadir la Solicitud");
                    }
                } catch (SQLException ex) {
                    System.out.println(ex);
                   Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(this, "La cantidad de Productos Solicitada,\n Supera a las existencias en Bodega");
            }
            
        }else if(rbPro_Bo.isSelected()){ // Para solicitar de Proveedor  a Bodega
            try {
                aProd.selectProd();
                tblSelectProv.setModel(aProd.getProvProd((DefaultTableModel) tblSelectProv.getModel()));
                tf_preCompra.setText(String.valueOf(aProd.getPreCompra()));
                frameSolicitaProd.setSize(585, 310);
                frameSolicitaProd.setLocationRelativeTo(null);
                frameSolicitaProd.setVisible(true);

            } catch (SQLException ex) {
                Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                
            }
        }else{
            JOptionPane.showMessageDialog(this, "No ha Seleccionado ningun un Producto");
        }
        try {
            btnProdSolicita.setText("Solicitudes Pendientes("+aProd.getSoliCant()+")");
        } catch (SQLException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_btnSolicitarProdActionPerformed

    private void btnProdSolicitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdSolicitaActionPerformed
        try {
            ProdSolicita frame = new ProdSolicita();
            frame.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnProdSolicitaActionPerformed
//</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc="Botones Add, Modific y Remove">
    private void btnDelProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelProdActionPerformed
        boolean r=false;
        if(tablaProd.isRowSelected(tablaProd.getSelectedRow())){
            
            DefaultTableModel model = (DefaultTableModel) tablaProd.getModel();
            idProd = Integer.parseInt(model.getValueAt(tablaProd.getSelectedRow(), 0).toString());
            int conf = JOptionPane.showConfirmDialog(this, "¿Está seguro de Eliminar este producto?");
            if(conf == 0){
                aProd.setCodigo(idProd);
                try {
                    r = aProd.rmovProd();
                } catch (SQLException ex) {
                    Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        if (r){
            JOptionPane.showMessageDialog(this, "Producto Eliminado Correctamente!");
        }else{
            JOptionPane.showMessageDialog(this, "No se Pudo Eliminar el Producto!");
        }
        
    }//GEN-LAST:event_btnDelProdActionPerformed

    private void btnAddProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProdActionPerformed
        this.idProd = 0;
        this.insertMode=true;
        try {
            Admin.AlterAddProd frame = new Admin.AlterAddProd();
            frame.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnAddProdActionPerformed

    private void btnModProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModProdActionPerformed
        fila = tablaProd.getSelectedRow();
        
        if(fila >=0){
            this.setIDProdTabla(fila);
            this.insertMode =false;
            
            try {
            Admin.AlterAddProd frame = new Admin.AlterAddProd();
            frame.setVisible(true);
            this.dispose();
            
        } catch (SQLException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
           
        }else{
            JOptionPane.showMessageDialog(this, "¡Selecione Un Producto!");
        }
        
    }//GEN-LAST:event_btnModProdActionPerformed
//</editor-fold>
    
    
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try {
            Usuarios f = new Usuarios();
            f.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        Estadisticas f;
        try {
            f = new Estadisticas();
            f.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.dispose();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void optLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optLogOutActionPerformed
        Admin.Login frame = new Admin.Login();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_optLogOutActionPerformed

    private void optUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optUsuariosActionPerformed
        try {                                           
            Usuarios f = new Usuarios();            
            f.setVisible(true);
            this.dispose();
            
        } catch (SQLException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_optUsuariosActionPerformed

    private void optProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optProveedoresActionPerformed
        try {
            Proveedores f = new Proveedores();
            f.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_optProveedoresActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        try {
            Admin.Estadisticas f = new Admin.Estadisticas();
            f.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            Admin.Marcas f = new Admin.Marcas();
            f.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void tfFindProdCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfFindProdCaretUpdate
        
        
    }//GEN-LAST:event_tfFindProdCaretUpdate

    private void tfFindProdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFindProdKeyTyped

    }//GEN-LAST:event_tfFindProdKeyTyped

    private void tfFindProdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFindProdKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try {   //Setear nuevamente el model al precionar el enter, capturando la busqueda;
                tablaProd.setModel(tablas.adminTablaProductos(model, tfFindProd.getText()));
                
            } catch (SQLException ex) {
                Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tfFindProdKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            tablaProd.setModel(tablas.adminTablaProductos(model,""));
        } catch (SQLException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnFindProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindProdActionPerformed
        try {
            tablaProd.setModel(tablas.adminTablaProductos(model, tfFindProd.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFindProdActionPerformed

    private void btnSoliProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoliProdActionPerformed
        int filaProv = tblSelectProv.getSelectedRow();

        if(filaProv<0){ //Proveedro seleccionado
            JOptionPane.showMessageDialog(frameSolicitaProd, "¡Seleccione un Proveedor!");

        }else{
            if(Float.valueOf(tf_preCompra.getText()) < 0.00f){ //Precio mayor que cero
                JOptionPane.showConfirmDialog(frameSolicitaProd, "El Precio No puede ser menor o igual a $0.00");
            }else{
            try {
                int cant = Integer.valueOf(spinCantSolicita.getValue().toString());
                String marca = model.getValueAt(fila, 2).toString();
                String prov = tblSelectProv.getModel().getValueAt(filaProv, 1).toString();
                Float precio = Float.valueOf(tf_preCompra.getText());

                if(aProd.solicitarProd("Proveedor", "Bodega", cant, marca, prov, precio)){
                    JOptionPane.showMessageDialog(this, "Añadido a Solicitudes Pendientes.");
                    tablaProd.clearSelection();
                    btnProdSolicita.setText("Solicitudes Pendientes("+aProd.getSoliCant()+")");
                    spinCantSolicita.setValue(0);
                    
                }else{
                    JOptionPane.showMessageDialog(this, "No se Pudo Añadir la Solicitud");
                    tablaProd.clearSelection();
                    spinCantSolicita.setValue(0);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
        }
    }//GEN-LAST:event_btnSoliProdActionPerformed

    private void btnCancelProvSoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelProvSoliActionPerformed
        frameSolicitaProd.setVisible(false);
    }//GEN-LAST:event_btnCancelProvSoliActionPerformed

    
    
    
    
    
    
    ////-----//----------------------------------------------------------------------//-----////
    private void setIDProdTabla(int fila){
        if (filtrado){
            //DefaultRowSorter rsModel = (DefaultRowSorter) tablaProd.getRowSorter().getModel();
            this.idProd = Integer.parseInt(tablaProd.getModel().getValueAt(fila,0).toString());
        }else{
            this.idProd = Integer.parseInt(tablaProd.getModel().getValueAt(fila, 0).toString());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Administracion().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
//<editor-fold desc="Declaracion de Variables">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProd;
    private javax.swing.JButton btnCancelProvSoli;
    private javax.swing.JButton btnDelProd;
    private javax.swing.JButton btnFindProd;
    private javax.swing.JButton btnModProd;
    private javax.swing.JButton btnProdSolicita;
    private javax.swing.JButton btnSoliProd;
    private javax.swing.JButton btnSolicitarProd;
    private javax.swing.JFrame frameSolicitaProd;
    private javax.swing.ButtonGroup gRBSolicita;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenuItem optLogOut;
    private javax.swing.JMenuItem optProveedores;
    private javax.swing.JMenuItem optUsuarios;
    private javax.swing.JRadioButton rbBo_Lo;
    private javax.swing.JRadioButton rbPro_Bo;
    private javax.swing.JSpinner spinCantSolicita;
    public static final javax.swing.JTable tablaProd = new javax.swing.JTable();
    private javax.swing.JTable tblSelectProv;
    private javax.swing.JTextField tfFindProd;
    private javax.swing.JTextField tf_preCompra;
    // End of variables declaration//GEN-END:variables

    
    //</editor-fold>
}
