/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Alumno
 */
public class Administracion extends javax.swing.JFrame {
    Funciones.Usuarios usuarios = new Funciones.Usuarios();
    Funciones.Productos aProd = new Funciones.Productos();
    Funciones.Tablas tablas = new Funciones.Tablas();
    Login login = new Login();
    public static boolean insertMode;
    public static int idProd;
    TableRowSorter filtro;
    
    //Variables para Realizar los procedimientos:
    float precioCompra, precioVenta, ganancia;
    
    public Administracion() throws SQLException{
        initComponents();
        this.setLocationRelativeTo(null);
        tablas.TablaProductos();
        gRBSolicita.add(rbBo_Lo); gRBSolicita.add(rbPro_Bo);
        btnProdSolicita.setText("Solicitudes Pendientes("+aProd.getSoliCant()+")");
        tablaProd.clearSelection();
        
        tablaProd.getColumnModel().getColumn(0).setMaxWidth(50);
        tablaProd.getColumnModel().getColumn(8).setMaxWidth(80);
        tablaProd.getColumnModel().getColumn(7).setMaxWidth(80);
        tablaProd.getColumnModel().getColumn(6).setMaxWidth(80);
        tablaProd.getColumnModel().getColumn(5).setMaxWidth(80);
        tablaProd.getColumnModel().getColumn(4).setMaxWidth(80);
        tablaProd.getColumnModel().getColumn(2).setMaxWidth(80);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gRBSolicita = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        tfFindProd = new javax.swing.JTextField();
        btnProdSolicita = new javax.swing.JButton();
        btnAddProd = new javax.swing.JButton();
        btnModProd = new javax.swing.JButton();
        btnDelProd = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rbBo_Lo = new javax.swing.JRadioButton();
        rbPro_Bo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        spinCantSolicita = new javax.swing.JSpinner();
        btnSolicitarProd = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        optLogOut = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        optUsuarios = new javax.swing.JMenuItem();
        optProveedores = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel de Administracion");

        tablaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Marca", "Proveedor", "Precio Compra", "Precio C/U", "Precio por Paquete", "Local Stock", "Bodega Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaProd);

        jLabel2.setText("Buscar");

        tfFindProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfFindProdKeyTyped(evt);
            }
        });

        btnProdSolicita.setText("Solicitudes Pendientes()");
        btnProdSolicita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdSolicitaActionPerformed(evt);
            }
        });

        btnAddProd.setText("Añadir Producto");
        btnAddProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdActionPerformed(evt);
            }
        });

        btnModProd.setText("Actualizar Producto");
        btnModProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModProdActionPerformed(evt);
            }
        });

        btnDelProd.setText("Remover Producto");
        btnDelProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelProdActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Solicitar Más Productos"));

        rbBo_Lo.setSelected(true);
        rbBo_Lo.setText("De Bodega a Local");

        rbPro_Bo.setText("De Proveedor A Bodega");

        jLabel1.setText("Cantidad:");

        spinCantSolicita.setValue(0);

        btnSolicitarProd.setText("Solicitar");
        btnSolicitarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbBo_Lo)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spinCantSolicita, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbPro_Bo)
                        .addGap(50, 50, 50)
                        .addComponent(btnSolicitarProd)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbBo_Lo)
                    .addComponent(jLabel1)
                    .addComponent(spinCantSolicita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbPro_Bo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnSolicitarProd)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ventas y Usuarios"));

        jButton12.setText("Usuarios");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Ventas");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton13)
                .addContainerGap())
        );

        jMenu1.setText("Archivo");

        optLogOut.setText("Cerrar Sesión");
        optLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optLogOutActionPerformed(evt);
            }
        });
        jMenu1.add(optLogOut);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Administrar");

        jMenuItem4.setText("Compras y Ventas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        optUsuarios.setText("Usuarios");
        optUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optUsuariosActionPerformed(evt);
            }
        });
        jMenu2.add(optUsuarios);

        optProveedores.setText("Proveedores");
        optProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optProveedoresActionPerformed(evt);
            }
        });
        jMenu2.add(optProveedores);

        jMenuItem1.setText("Marcas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(169, 169, 169)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnDelProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnModProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAddProd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfFindProd, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnProdSolicita)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfFindProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProdSolicita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelProd))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc="Metodos para la solicitud de productos">
    
    private void btnSolicitarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarProdActionPerformed
      
        DefaultTableModel model = (DefaultTableModel) tablaProd.getModel();
        int fila = tablaProd.getSelectedRow();
        //Obtener el ID de Producto.
        if(fila>=0){
            
            aProd.setCodigo(Integer.valueOf(model.getValueAt(fila, 0).toString()));
            
            int bodeCant = Integer.parseInt(model.getValueAt(fila, 8).toString());
            int cant = Integer.parseInt(spinCantSolicita.getValue().toString());
            
            String marca = model.getValueAt(fila, 2).toString();
            String provs = model.getValueAt(fila, 3).toString();
            
            if(rbBo_Lo.isSelected()){
                if(cant<=bodeCant){
                    try {
                        aProd.selectProd();
                        if(aProd.solicitarProd("Bodega", "Local", cant, marca, provs)){
                            JOptionPane.showMessageDialog(this, "Añadido a Solicitudes Pendientes.");
                        }else{
                            JOptionPane.showMessageDialog(this, "No se Pudo Añadir la Solicitud");
                        }
                    } catch (SQLException ex) {
                        System.out.println(ex);
                       Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "La cantidad de Productos Solicitada,\n Supera a las existencias en Bodega");
                }           
            }else if(rbPro_Bo.isSelected()){
                try {
                    
                    aProd.selectProd();
                    if(aProd.solicitarProd("Proveedor", "Bodega", cant, marca, provs)){
                        JOptionPane.showMessageDialog(this, "Añadido a Solicitudes Pendientes.");
                    }else{
                        JOptionPane.showMessageDialog(this, "No se Pudo Añadir la Solicitud");
                    }
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "No ha Seleccionado ningun un Producto");
        }
        try {
            btnProdSolicita.setText("Solicitudes Pendientes("+aProd.getSoliCant()+")");
        } catch (SQLException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
        tablaProd.clearSelection();
        spinCantSolicita.setValue(0);
        
        
    }//GEN-LAST:event_btnSolicitarProdActionPerformed

    private void btnProdSolicitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdSolicitaActionPerformed
        try {
            ProdSolicita frame = new ProdSolicita();
            frame.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnProdSolicitaActionPerformed
//</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc="Botones Add, Modific y Remove">
    private void btnDelProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelProdActionPerformed
        boolean r=false;
        if(tablaProd.isRowSelected(tablaProd.getSelectedRow())){
            
            DefaultTableModel model = (DefaultTableModel) tablaProd.getModel();
            idProd = Integer.parseInt(model.getValueAt(tablaProd.getSelectedRow(), 0).toString());
            int conf = JOptionPane.showConfirmDialog(this, "¿Está seguro de Eliminar este producto?");
            if(conf == 0){
                aProd.setCodigo(idProd);
                try {
                    r = aProd.rmovProd();
                } catch (SQLException ex) {
                    Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        if (r){
            JOptionPane.showMessageDialog(this, "Producto Eliminado Correctamente!");
        }else{
            JOptionPane.showMessageDialog(this, "No se Pudo Eliminar el Producto!");
        }
        
    }//GEN-LAST:event_btnDelProdActionPerformed

    private void btnAddProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProdActionPerformed
        this.idProd = 0;
        this.insertMode=true;
        try {
            Admin.AlterAddProd frame = new Admin.AlterAddProd();
            frame.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnAddProdActionPerformed

    private void btnModProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModProdActionPerformed
        int fila = tablaProd.getSelectedRow();
        if(fila >=0){
            DefaultTableModel model = (DefaultTableModel) tablaProd.getModel();
            this.idProd = Integer.parseInt(model.getValueAt(fila, 0).toString());
            this.insertMode =false;
            
            try {
            Admin.AlterAddProd frame = new Admin.AlterAddProd();
            frame.setVisible(true);
            this.dispose();
            
        } catch (SQLException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
           
        }else{
            JOptionPane.showMessageDialog(this, "¡Selecione Un Producto!");
        }
        
    }//GEN-LAST:event_btnModProdActionPerformed
//</editor-fold>
    
    
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        Estadisticas f;
        try {
            f = new Estadisticas();
            f.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.dispose();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void tfFindProdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFindProdKeyTyped
        tfFindProd.addKeyListener(new KeyAdapter() {
        public void keyReleased(final KeyEvent e){
            tfFindProd.setText(tfFindProd.getText());
            repaint();
            filtro.setRowFilter(RowFilter.regexFilter(tfFindProd.getText().trim(), 1));
        }
        });
        filtro = new TableRowSorter(tablaProd.getModel());
        tablaProd.setRowSorter(filtro);
    }//GEN-LAST:event_tfFindProdKeyTyped

    private void optLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optLogOutActionPerformed
        Admin.Login frame = new Admin.Login();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_optLogOutActionPerformed

    private void optUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optUsuariosActionPerformed
        try {                                           
            Usuarios f = new Usuarios();            
            f.setVisible(true);
            this.dispose();
            
        } catch (SQLException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_optUsuariosActionPerformed

    private void optProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optProveedoresActionPerformed
        try {
            Proveedores f = new Proveedores();
            f.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_optProveedoresActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        try {
            Admin.Estadisticas f = new Admin.Estadisticas();
            f.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            Admin.Marcas f = new Admin.Marcas();
            f.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Administracion().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
//<editor-fold desc="Declaracion de Variables">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProd;
    private javax.swing.JButton btnDelProd;
    private javax.swing.JButton btnModProd;
    private javax.swing.JButton btnProdSolicita;
    private javax.swing.JButton btnSolicitarProd;
    private javax.swing.ButtonGroup gRBSolicita;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem optLogOut;
    private javax.swing.JMenuItem optProveedores;
    private javax.swing.JMenuItem optUsuarios;
    private javax.swing.JRadioButton rbBo_Lo;
    private javax.swing.JRadioButton rbPro_Bo;
    private javax.swing.JSpinner spinCantSolicita;
    public static final javax.swing.JTable tablaProd = new javax.swing.JTable();
    private javax.swing.JTextField tfFindProd;
    // End of variables declaration//GEN-END:variables

    private void Solicitar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    //</editor-fold>
}
