/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.math.RoundingMode;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Mauricio Cruz
 */
public class AlterAddProd extends javax.swing.JFrame {

    Funciones.Usuarios usuarios = new Funciones.Usuarios();
    Funciones.Productos aProd = new Funciones.Productos();
    Funciones.Tablas tablas = new Funciones.Tablas();
    DefaultTableModel modelMarca, modelProv;
    Login login = new Login();
    public boolean insertMode;
    public int idProd;
    float precioCompra, precioVenta, ganancia;
    DecimalFormat df= new DecimalFormat("#####.##");
    private TableRowSorter filtro;
    private boolean p1=false, p2=false, p3=false, p4=false, marka=false;

    public void setIdProd(int idProd) {
        this.idProd = idProd;
    }
    public void setInsertMode(boolean insertMode) {
        this.insertMode = insertMode;
    }
    
    
    
    //<editor-fold defaultstate="collapsed" desc="METODO CONSTRUCTOR">
    public AlterAddProd() throws SQLException {
        initComponents();
        df.setRoundingMode(RoundingMode.UP);
        Admin.Administracion frame = new Admin.Administracion();
        this.idProd = frame.idProd;
        this.setIconImage(new ImageIcon(getClass().getResource("../Imagenes/iconos/logo.png")).getImage());
        this.insertMode = frame.insertMode;
        
        FrameMarcas.setVisible(false);
        this.setLocationRelativeTo(null);
        
        modelProv = (DefaultTableModel) this.tablaProvLista.getModel();
        modelMarca = (DefaultTableModel) this.tablaMarcas.getModel();
        
        tablaProvLista.getColumnModel().getColumn(0).setMaxWidth(50); //Ocultar la Columna de ID
        
        if(insertMode){
            lblCodigo.setText("Codigo: --Nuevo Registro--");
            
            tablaMarcas.setModel(aProd.llenarMarcas(modelMarca));
            this.tablaProvLista.setModel(aProd.llenarProvs_(modelProv, ""));
            
        }else{
            aProd.setCodigo(idProd);
            aProd.selectProd();
            llenarCampos();
            this.tablaProvLista.setModel(aProd.llenarProvs_(modelProv, ""));
            this.tablaMarcas.setModel(aProd.llenarMarcas(modelMarca));
        }      
    }//</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameMarcas = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMarcas = new javax.swing.JTable();
        txtFindMarca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnMarcaOk = new javax.swing.JButton();
        btnMarCancel = new javax.swing.JButton();
        btnAddMarca = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtProdNombre = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        btnMarca = new javax.swing.JButton();
        txtPreVenta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPreCompra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        spinLocal = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        spinBodega = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        spinRepos = new javax.swing.JSpinner();
        btnCancelModProd = new javax.swing.JButton();
        btnSaveModProd = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProvLista = new javax.swing.JTable();
        txtProvFind = new javax.swing.JTextField();
        btnProv1 = new javax.swing.JButton();
        btnProv2 = new javax.swing.JButton();
        btnProv3 = new javax.swing.JButton();
        btnProv4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblProv1 = new javax.swing.JLabel();
        lblProv2 = new javax.swing.JLabel();
        lblProv3 = new javax.swing.JLabel();
        lblProv4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        spinPack = new javax.swing.JSpinner();
        txtPrePack = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        spinGanancia = new javax.swing.JSpinner();
        lblSugPrecio = new javax.swing.JLabel();
        lblDiferencia = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        FrameMarcas.setTitle("Seleccionar Marca");
        FrameMarcas.setMinimumSize(new java.awt.Dimension(429, 300));

        tablaMarcas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Marca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaMarcas);
        if (tablaMarcas.getColumnModel().getColumnCount() > 0) {
            tablaMarcas.getColumnModel().getColumn(0).setResizable(false);
            tablaMarcas.getColumnModel().getColumn(1).setResizable(false);
        }

        txtFindMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFindMarcaKeyPressed(evt);
            }
        });

        jLabel2.setText("Buscar:");

        btnMarcaOk.setText("Seleccionar");
        btnMarcaOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcaOkActionPerformed(evt);
            }
        });

        btnMarCancel.setText("Cancelar");
        btnMarCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarCancelActionPerformed(evt);
            }
        });

        btnAddMarca.setText("Agregar");
        btnAddMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMarcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrameMarcasLayout = new javax.swing.GroupLayout(FrameMarcas.getContentPane());
        FrameMarcas.getContentPane().setLayout(FrameMarcasLayout);
        FrameMarcasLayout.setHorizontalGroup(
            FrameMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameMarcasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(FrameMarcasLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFindMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FrameMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMarcaOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMarCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        FrameMarcasLayout.setVerticalGroup(
            FrameMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameMarcasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFindMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FrameMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FrameMarcasLayout.createSequentialGroup()
                        .addComponent(btnMarcaOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddMarca)
                        .addGap(18, 18, 18)
                        .addComponent(btnMarCancel)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestionar Producto");
        setUndecorated(true);

        lblCodigo.setText("Codigo:");

        jLabel4.setText("*Nombre:");

        lblMarca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMarca.setText(" ");

        btnMarca.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnMarca.setText("Seleccionar");
        btnMarca.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcaActionPerformed(evt);
            }
        });

        txtPreVenta.setText("0.0");
        txtPreVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPreVentaKeyTyped(evt);
            }
        });

        jLabel8.setText("*Precio de Venta: $");

        txtPreCompra.setText("0.0");
        txtPreCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPreCompraKeyTyped(evt);
            }
        });

        jLabel7.setText("*Precio de Compra: $");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Existencias"));

        jLabel9.setText("*En Local:");

        jLabel10.setText("En Bodega:");

        jLabel11.setText("*Min. Reposicion");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinBodega, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinRepos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(spinLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(spinBodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(spinRepos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancelModProd.setText("Cancelar");
        btnCancelModProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelModProdActionPerformed(evt);
            }
        });

        btnSaveModProd.setText("Guardar");
        btnSaveModProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveModProdActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Proveedores de Producto"));

        tablaProvLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Proveedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaProvLista);
        if (tablaProvLista.getColumnModel().getColumnCount() > 0) {
            tablaProvLista.getColumnModel().getColumn(0).setResizable(false);
        }

        txtProvFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProvFindKeyPressed(evt);
            }
        });

        btnProv1.setText("Proveedor 1");
        btnProv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProv1ActionPerformed(evt);
            }
        });

        btnProv2.setText("Proveedor 2");
        btnProv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProv2ActionPerformed(evt);
            }
        });

        btnProv3.setText("Proveedor 3");
        btnProv3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProv3ActionPerformed(evt);
            }
        });

        btnProv4.setText("Proveedor 4");
        btnProv4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProv4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar:");

        lblProv1.setText(" ");

        lblProv2.setText(" ");

        lblProv3.setText(" ");

        lblProv4.setText(" ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProvFind)
                            .addComponent(btnProv1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(btnProv2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProv3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProv4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblProv4))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblProv2)
                                    .addComponent(lblProv3)
                                    .addComponent(lblProv1)))))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProvFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProv1)
                            .addComponent(lblProv1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProv2)
                            .addComponent(lblProv2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProv3)
                            .addComponent(lblProv3))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProv4)
                            .addComponent(lblProv4))))
                .addGap(318, 318, 318))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio por Paquete de Unidades"));

        jLabel19.setText("Unidades:");

        jLabel20.setText("Precio: $");

        txtPrePack.setText("0.0");
        txtPrePack.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrePackKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrePack))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinPack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(spinPack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtPrePack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio según % de Ganancia"));

        jLabel12.setText("% de Ganancia");

        spinGanancia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinGananciaStateChanged(evt);
            }
        });

        lblSugPrecio.setText("Precio Sugerido: $");
        lblSugPrecio.setAutoscrolls(true);

        lblDiferencia.setText("  Diferencia: $");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSugPrecio)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(spinGanancia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12))
                    .addComponent(lblDiferencia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinGanancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSugPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDiferencia)
                .addContainerGap())
        );

        jLabel3.setText("Marca:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(lblCodigo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPreCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPreVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addComponent(btnSaveModProd)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelModProd))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtProdNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblMarca)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnMarca)))))
                        .addGap(0, 106, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtProdNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblMarca)
                    .addComponent(btnMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPreCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtPreVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveModProd)
                    .addComponent(btnCancelModProd))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcaActionPerformed
        try {
            if(marka){
                aProd.setMarcaDB(0);
                lblMarca.setText(" ");
                btnMarca.setText("Seleccionar");
                marka = false; //falso porque se elimina,... ya no hay proveedor 
            }else{
                
                tablaMarcas.setModel(aProd.llenarMarcas(modelMarca));
                txtFindMarca.setText("");
                this.FrameMarcas.setLocationRelativeTo(null);
                this.FrameMarcas.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AlterAddProd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMarcaActionPerformed
//<editor-fold defaultstate="collapsed" desc="(TextFields)Validaciones para Ingresar solo Numeros">
    private void txtPreVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPreVentaKeyTyped
        validaNum(evt);
    }//GEN-LAST:event_txtPreVentaKeyTyped

    private void txtPreCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPreCompraKeyTyped
        validaNum(evt);
    }//GEN-LAST:event_txtPreCompraKeyTyped

    private void txtPrePackKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrePackKeyTyped
        validaNum(evt);
    }//GEN-LAST:event_txtPrePackKeyTyped
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc="Boton de Guardado y Cancelar">
    private void spinGananciaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinGananciaStateChanged
        precioCompra = Float.parseFloat(txtPreCompra.getText());
        int f = Integer.parseInt(String.valueOf(spinGanancia.getValue()));
        String gan="0.";
        if(f<10){  gan += "0"; }
        gan += String.valueOf(f);
        ganancia = precioCompra* Float.parseFloat(gan);
        float preVFinal =(precioCompra +ganancia);

        precioVenta = Float.valueOf(df.format(preVFinal));
        txtPreVenta.setText(String.valueOf(precioVenta));
        lblSugPrecio.setText("Precio Sugerido: $"+df.format(precioVenta));
        lblDiferencia.setText("Diferencia: $"+df.format(ganancia));
    }//GEN-LAST:event_spinGananciaStateChanged

    private void btnSaveModProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveModProdActionPerformed
        String campos = "";
        boolean control = true;
        //Validar y Capturar los Datos y Settearlos en el EntityClass
        if (!txtProdNombre.getText().equals("")){
            aProd.setNombre(txtProdNombre.getText());
        }else{
            campos+= "\n*Nombre de Producto";
            control=false;
        }

        //Validacion para los precios de tipo Floats
        if(!txtPreCompra.getText().equals("0") && !txtPreCompra.getText().equals("0.0") && !txtPreCompra.getText().equals("")){
            if(txtPreCompra.getText().contains(".")){
                aProd.setPreCompra(Float.parseFloat(txtPreCompra.getText()));
            }else{
                aProd.setPreCompra(Float.parseFloat(txtPreCompra.getText()+".0"));
            }

        }else{
            campos += "\n*Precio de Compra";
            control = false;
        }

        //Setear venta
        if(!txtPreVenta.getText().equals("0") && !txtPreVenta.getText().equals("0.0") && !txtPreVenta.getText().equals("")){
            if(txtPreVenta.getText().contains(".")){
                aProd.setPreVenta(Float.parseFloat(txtPreVenta.getText()));
            }else{
                aProd.setPreVenta(Float.parseFloat(txtPreVenta.getText()+".0"));
            }

        }else{
            campos += "\n*Precio de Venta";
            control =false;
        }

        if(!txtPrePack.getText().equals("")){
            if(txtPrePack.getText().contains(".")){
                aProd.setPrePack(Float.parseFloat(txtPrePack.getText()));
            }else{
                aProd.setPrePack(Float.parseFloat(txtPrePack.getText()+".00"));
            }
        }

        //Validaion para los Spinner
        if(!spinLocal.getValue().toString().equals("0") && !spinLocal.getValue().toString().equals("")){
            aProd.setLocalCant(Integer.parseInt(spinLocal.getValue().toString()));
        }else{
            campos += "\n*Existencias en Local";
            control = false;
        }

        if(!spinRepos.getValue().toString().equals("0") && !spinRepos.getValue().toString().equals("")){
            aProd.setRepo(Integer.parseInt(spinRepos.getValue().toString()));
        }else{
            campos += "\n*Minimo de Reposición";
            control=false;
        }

        //Settear los Que no necesitan de Validacion.
        aProd.setCantPack(Integer.parseInt(spinPack.getValue().toString()));
        aProd.setPorceGan(Integer.parseInt(spinGanancia.getValue().toString()));
        aProd.setBodegaCant(Integer.parseInt(spinBodega.getValue().toString()));
        boolean r=false;
        String res="";

        if (control){
            try {

                if(insertMode){
                    r=aProd.addProd();
                    res="¡Producto Registrado!";
                }else{
                    r=aProd.modProd();
                    res="¡Producto Modificado!";
                }

                JOptionPane.showMessageDialog(this, res);
                aProd.deselectProd();
                Admin.Administracion frame = new Admin.Administracion();
                frame.setVisible(true);
                this.dispose();

            } catch (SQLException ex) {
                System.out.println("error: "+ex);
                JOptionPane.showMessageDialog(this, "¡No se pudo Realizar la Consulta!...\n Compruebe que los datos que ingresa son correctos");
                Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Ha Olvidado llenar estos Campos Obligatorios:" + campos);
        }
    }//GEN-LAST:event_btnSaveModProdActionPerformed

    private void btnCancelModProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelModProdActionPerformed
        try {
            this.idProd=0;
            aProd.deselectProd();
            Admin.Administracion frame = new Admin.Administracion();
            frame.idProd = 0;
            frame.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(AlterAddProd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCancelModProdActionPerformed
    //</editor-fold>
    
   //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc="(Botones)Metodos para Seleccionar Proveedores">
    private void btnProv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProv1ActionPerformed
         // TODO add your handling code here:
         int fila = tablaProvLista.getSelectedRow();
         
         
         if(p1){//Si e sverdadero, es porque ya hay un proveedor. por lo tanto, vamo a borrarlo
             aProd.setDbProv1(0);
             lblProv1.setText("");
             btnProv1.setText("Proveedor 1");
             p1 = false; //falso porque se elimina,... ya no hay proveedor 
                    
         }else{ //En caso de que no exista un Proveeedor Actualmente
             if(fila>=0){
                 int id= Integer.valueOf(modelProv.getValueAt(fila, 0).toString());
                 aProd.setDbProv1(id);  //setear el id del Proveedor
                 p1=true; //true por que ahora se setea
                 try {
                    lblProv1.setText(">>> " + aProd.getProvNombre(id));
                    btnProv1.setText("Quitar Proveedor");
                 } catch (SQLException ex) {
                     Logger.getLogger(AlterAddProd.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }else{
                 JOptionPane.showMessageDialog(this, "Selecione un Proveedor de la lista");
             }
             
         }
         tablaProvLista.clearSelection();
    }//GEN-LAST:event_btnProv1ActionPerformed

    private void btnProv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProv2ActionPerformed
        int fila = tablaProvLista.getSelectedRow();
         
         
         if(p2){//Si e sverdadero, es porque ya hay un proveedor. por lo tanto, vamo a borrarlo
             aProd.setDbProv2(0);
             lblProv2.setText("");
             btnProv2.setText("Proveedor 2");
             p2 = false; //falso porque se elimina,... ya no hay proveedor 
                    
         }else{ //En caso de que no exista un Proveeedor Actualmente
             if(fila>=0){
                 int id= Integer.valueOf(modelProv.getValueAt(fila, 0).toString());
                 aProd.setDbProv2(id);  //setear el id del Proveedor
                 p2=true; //true por que ahora se setea
                 try {
                    lblProv2.setText(">>> " + aProd.getProvNombre(id));
                    btnProv2.setText("Quitar Proveedor");
                 } catch (SQLException ex) {
                     Logger.getLogger(AlterAddProd.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }else{
                 JOptionPane.showMessageDialog(this, "Selecione un Proveedor de la lista");
             }
         }
         tablaProvLista.clearSelection();
    }//GEN-LAST:event_btnProv2ActionPerformed

    private void btnProv3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProv3ActionPerformed
        int fila = tablaProvLista.getSelectedRow();
         
         
         if(p3){//Si e sverdadero, es porque ya hay un proveedor. por lo tanto, vamo a borrarlo
             aProd.setDbProv3(0);
             lblProv3.setText("");
             btnProv3.setText("Proveedor 3");
             p3 = false; //falso porque se elimina,... ya no hay proveedor 
                    
         }else{ //En caso de que no exista un Proveeedor Actualmente
             if(fila>=0){
                 int id= Integer.valueOf(modelProv.getValueAt(fila, 0).toString());
                 aProd.setDbProv3(id);  //setear el id del Proveedor
                 p3=true; //true por que ahora se setea
                 try {
                    lblProv3.setText(">>> " + aProd.getProvNombre(id));
                    btnProv3.setText("Quitar Proveedor");
                 } catch (SQLException ex) {
                     Logger.getLogger(AlterAddProd.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }else{
                 JOptionPane.showMessageDialog(this, "Selecione un Proveedor de la lista");
             }
         }
         tablaProvLista.clearSelection();
    }//GEN-LAST:event_btnProv3ActionPerformed

    private void btnProv4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProv4ActionPerformed
         int fila = tablaProvLista.getSelectedRow();
         
         
         if(p4){//Si e sverdadero, es porque ya hay un proveedor. por lo tanto, vamo a borrarlo
             aProd.setDbProv4(0);
             lblProv4.setText("");
             btnProv4.setText("Proveedor 4");
             p4 = false; //falso porque se elimina,... ya no hay proveedor 
                    
         }else{ //En caso de que no exista un Proveeedor Actualmente
             if(fila>=0){
                 
                 int id= Integer.valueOf(modelProv.getValueAt(fila, 0).toString());
                 aProd.setDbProv4(id);  //setear el id del Proveedor
                 p4=true; //true por que ahora se setea
                 try {
                    lblProv4.setText(">>> " + aProd.getProvNombre(id));
                    btnProv4.setText("Quitar Proveedor");
                 } catch (SQLException ex) {
                     Logger.getLogger(AlterAddProd.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }else{
                 JOptionPane.showMessageDialog(this, "Selecione un Proveedor de la lista");
             }
         }
         tablaProvLista.clearSelection();
    }//GEN-LAST:event_btnProv4ActionPerformed
    //</editor-fold>
    
    
    private void btnMarcaOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcaOkActionPerformed
         int fila = tablaMarcas.getSelectedRow();
         
             if(fila>=0){
                 
                 int id= Integer.parseInt(modelMarca.getValueAt(fila, 0).toString());
                 tablaMarcas.clearSelection();
                 try {
                    aProd.setMarcaDB(id);  //setear el id del Proveedor
                    marka=true; //true por que ahora se setea
                    btnMarca.setText("Quitar");
                 
                    lblMarca.setText(aProd.getMarcaNombre());
                    FrameMarcas.setVisible(false);
                 } catch (SQLException ex) {
                     Logger.getLogger(AlterAddProd.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }else{
                 JOptionPane.showMessageDialog(this.FrameMarcas, "Selecione una Marca de la lista");
             }
         
    }//GEN-LAST:event_btnMarcaOkActionPerformed

    private void btnMarCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarCancelActionPerformed
        tablaMarcas.clearSelection();
        FrameMarcas.setVisible(false);
    }//GEN-LAST:event_btnMarCancelActionPerformed

    private void btnAddMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMarcaActionPerformed
        String marca = JOptionPane.showInputDialog("Ingrese la Nueva Marca");
        if(!marca.equals("")){
            if(aProd.addMarca(marca)){
                JOptionPane.showMessageDialog(this.FrameMarcas, "¡Marca Agregada!");
                tablaMarcas.setModel(modelMarca);
            }else{
                JOptionPane.showMessageDialog(this.FrameMarcas, "No se Pudo Agregar la Marca");
            }
        }
    }//GEN-LAST:event_btnAddMarcaActionPerformed

    private void txtFindMarcaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindMarcaKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try {   //Setear nuevamente el model al precionar el enter, capturando la busqueda;
                tablaMarcas.setModel(tablas.Marcas(modelMarca, this.txtFindMarca.getText()));
                
            } catch (SQLException ex) {
                Logger.getLogger(AlterAddProd.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtFindMarcaKeyPressed

    private void txtProvFindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvFindKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try {
                this.tablaProvLista.setModel(aProd.llenarProvs_(modelProv, txtProvFind.getText()));
            } catch (SQLException ex) {
                Logger.getLogger(Marcas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtProvFindKeyPressed
    //</editor-fold>
    
    //-------------------------------Campos para -------------------------------------//
    //<editor-fold defaultstate="collapsed" desc="Metodos limpiar, rellenar y validar campos">
    public void limpiarCampos(){
        txtProdNombre.setText("");
        lblCodigo.setText("Codigo: ");
        txtPreCompra.setText("0");
        txtPreVenta.setText("0");
        spinGanancia.setValue(0);
        lblSugPrecio.setText("Precio Sugerido: $");
        lblDiferencia.setText("Diferencia: $");
        spinPack.setValue(0);
        txtPrePack.setText("0");
        spinLocal.setValue(0); spinBodega.setValue(0); spinRepos.setValue(0);
                
    }
    
    
    
    public void llenarCampos() throws SQLException{     
        
        txtProdNombre.setText(aProd.getNombre());
        lblCodigo.setText("Codigo: "+aProd.getCodigo());
        txtPreCompra.setText(String.valueOf(aProd.getPreCompra()));
        txtPreVenta.setText(String.valueOf(aProd.getPreVenta()));
        spinGanancia.setValue(aProd.getPorceGan());
        spinPack.setValue(aProd.getCantPack());
        txtPrePack.setText(String.valueOf(aProd.getPrePack()));
        spinLocal.setValue(aProd.getLocalCant());
        spinBodega.setValue(aProd.getBodegaCant());
        spinRepos.setValue(aProd.getRepo());
        
        //Para los Label de los Proveedores
        
        if(!aProd.getProv1().equals("")){
             lblProv1.setText(">>> "+aProd.getProv1());
             p1=true;
         }else{
             lblProv1.setText(" ");
             p1=false;
         }
        
        if(!aProd.getProv2().equals("")){
             lblProv2.setText(">>> "+aProd.getProv2());
             p2=true;
         }else{
             lblProv2.setText(" ");
             p2=false;
         }
        
        if(!aProd.getProv3().equals("")){
             lblProv3.setText(">>> "+aProd.getProv3());
             p3=true;
             
         }else{
             lblProv3.setText(" ");
             p3=false;
         }
        
        if(!aProd.getProv4().equals("")){
             lblProv4.setText(">>> "+aProd.getProv4());
             p4=true;
         }else{
             lblProv4.setText(" ");
             p4=false;
         }
        if(!aProd.getMarca().equals("")){
            marka=true;
            lblMarca.setText(aProd.getMarca());
            btnMarca.setText("Quitar");
        }else{
            marka=false;
            lblMarca.setText("");
            btnMarca.setText("Seleccionar");
        }
    }
    //Validacion para que no se puedan ingresar letras al jTextField
    
    private void validaNum(java.awt.event.KeyEvent evt){
        char val=evt.getKeyChar();
        if (Character.isLetter(val)){
            getToolkit().beep();
            evt.consume();
        }
    }
    //</editor-fold>
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterAddProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterAddProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterAddProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterAddProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AlterAddProd().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AlterAddProd.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    //<editor-fold defaultstate="collapsed" desc="Declaracion de Objetos JavaSwing">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame FrameMarcas;
    private javax.swing.JButton btnAddMarca;
    private javax.swing.JButton btnCancelModProd;
    private javax.swing.JButton btnMarCancel;
    private javax.swing.JButton btnMarca;
    private javax.swing.JButton btnMarcaOk;
    private javax.swing.JButton btnProv1;
    private javax.swing.JButton btnProv2;
    private javax.swing.JButton btnProv3;
    private javax.swing.JButton btnProv4;
    private javax.swing.JButton btnSaveModProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDiferencia;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblProv1;
    private javax.swing.JLabel lblProv2;
    private javax.swing.JLabel lblProv3;
    private javax.swing.JLabel lblProv4;
    private javax.swing.JLabel lblSugPrecio;
    private javax.swing.JSpinner spinBodega;
    private javax.swing.JSpinner spinGanancia;
    private javax.swing.JSpinner spinLocal;
    private javax.swing.JSpinner spinPack;
    private javax.swing.JSpinner spinRepos;
    private javax.swing.JTable tablaMarcas;
    public javax.swing.JTable tablaProvLista;
    private javax.swing.JTextField txtFindMarca;
    private javax.swing.JTextField txtPreCompra;
    private javax.swing.JTextField txtPrePack;
    private javax.swing.JTextField txtPreVenta;
    private javax.swing.JTextField txtProdNombre;
    private javax.swing.JTextField txtProvFind;
    // End of variables declaration//GEN-END:variables
}//</editor-fold>
