/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.awt.Image;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Mauricio Cruz
 */
public class AlterAddProd extends javax.swing.JFrame {

    Funciones.Usuarios usuarios = new Funciones.Usuarios();
    Funciones.Productos aProd = new Funciones.Productos();
    Funciones.Tablas tablas = new Funciones.Tablas();
    Login login = new Login();
    public static boolean insertMode;
    public static int idProd=0;
    float precioCompra, precioVenta, ganancia;
    private TableRowSorter filtro;
    private boolean p1=false, p2=false, p3=false, p4=false;
    
    
    
    public AlterAddProd() throws SQLException {
        initComponents();
        Admin.Administracion frame = new Admin.Administracion();
        this.insertMode = frame.insertMode;
        this.idProd = frame.idProd;
        this.setLocationRelativeTo(null);
        DefaultTableModel model = (DefaultTableModel) tablaProvLista.getModel();
        DefaultTableModel modelProvSel = (DefaultTableModel) tablaProvLista.getModel();
        
        if(idProd>0){
            aProd.setCodigo(idProd);
            aProd.selectProd();
            llenarCampos();
            this.tablaProvLista.setModel(aProd.llenarProvs_(model));
            
        }else{
            tablaProvLista.setModel(aProd.llenarProvs_(model));
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtProdNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        txtPreVenta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPreCompra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        spinLocal = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        spinBodega = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        spinRepos = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProvLista = new javax.swing.JTable();
        txtProvFind = new javax.swing.JTextField();
        btnProv1 = new javax.swing.JButton();
        btnProv2 = new javax.swing.JButton();
        btnProv3 = new javax.swing.JButton();
        btnProv4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblProv1 = new javax.swing.JLabel();
        lblProv2 = new javax.swing.JLabel();
        lblProv3 = new javax.swing.JLabel();
        lblProv4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        spinPack = new javax.swing.JSpinner();
        txtPrePack = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        spinGanancia = new javax.swing.JSpinner();
        lblSugPrecio = new javax.swing.JLabel();
        lblDiferencia = new javax.swing.JLabel();
        btnSaveModProd = new javax.swing.JButton();
        btnCancelModProd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        lblCodigo.setText("Codigo:");

        jLabel4.setText("*Nombre:");

        jLabel5.setText("Marca:");

        jButton6.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jButton6.setText("+");
        jButton6.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jButton7.setText("-");
        jButton7.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        txtPreVenta.setText("0.0");
        txtPreVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPreVentaKeyTyped(evt);
            }
        });

        jLabel8.setText("*Precio de Venta: $");

        txtPreCompra.setText("0.0");
        txtPreCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPreCompraKeyTyped(evt);
            }
        });

        jLabel7.setText("*Precio de Compra: $");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Existencias"));

        jLabel9.setText("*En Local:");

        jLabel10.setText("En Bodega:");

        jLabel11.setText("*Min. Reposicion");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinBodega, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinRepos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(spinLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(spinBodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(spinRepos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Proveedores de Producto"));

        tablaProvLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Proveedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaProvLista);

        txtProvFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProvFindKeyTyped(evt);
            }
        });

        btnProv1.setText("Proveedor 1");
        btnProv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProv1ActionPerformed(evt);
            }
        });

        btnProv2.setText("Proveedor 2");

        btnProv3.setText("Proveedor 3");

        btnProv4.setText("Proveedor 4");

        jLabel1.setText("Buscar:");

        lblProv1.setText(" ");

        lblProv2.setText(" ");

        lblProv3.setText(" ");

        lblProv4.setText(" ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProvFind)
                            .addComponent(btnProv1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(btnProv2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProv3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProv4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProv1)
                            .addComponent(lblProv2)
                            .addComponent(lblProv3)
                            .addComponent(lblProv4)))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProvFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProv1)
                            .addComponent(lblProv1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProv2)
                            .addComponent(lblProv2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProv3)
                            .addComponent(lblProv3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProv4)
                            .addComponent(lblProv4))
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio por Paquete de Unidades"));

        jLabel19.setText("Unidades:");

        jLabel20.setText("Precio: $");

        txtPrePack.setText("0.0");
        txtPrePack.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrePackKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrePack))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinPack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(spinPack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtPrePack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio según % de Ganancia"));

        jLabel12.setText("% de Ganancia");

        spinGanancia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinGananciaStateChanged(evt);
            }
        });

        lblSugPrecio.setText("Precio Sugerido: $");
        lblSugPrecio.setAutoscrolls(true);

        lblDiferencia.setText("  Diferencia: $");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSugPrecio)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(spinGanancia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12))
                    .addComponent(lblDiferencia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinGanancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSugPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDiferencia)
                .addContainerGap())
        );

        btnSaveModProd.setText("Guardar");
        btnSaveModProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveModProdActionPerformed(evt);
            }
        });

        btnCancelModProd.setText("Cancelar");
        btnCancelModProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelModProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(layout.createSequentialGroup()
                    .addGap(149, 149, 149)
                    .addComponent(btnSaveModProd)
                    .addGap(48, 48, 48)
                    .addComponent(btnCancelModProd)
                    .addGap(658, 692, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(lblCodigo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPreCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPreVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProdNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(302, 471, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtProdNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPreCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtPreVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveModProd)
                    .addComponent(btnCancelModProd))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        JOptionPane.showInputDialog("Nueva Marca:");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        JOptionPane.showMessageDialog(this, "Hay productos registrados bajo esta marca... \nElimine primero estos productos antes de eliminar la Marca");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txtPreVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPreVentaKeyTyped
        validaNum(evt);
    }//GEN-LAST:event_txtPreVentaKeyTyped

    private void txtPreCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPreCompraKeyTyped
        validaNum(evt);
    }//GEN-LAST:event_txtPreCompraKeyTyped

    private void txtPrePackKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrePackKeyTyped
        validaNum(evt);
    }//GEN-LAST:event_txtPrePackKeyTyped

    private void spinGananciaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinGananciaStateChanged
        precioCompra = Float.parseFloat(txtPreCompra.getText());
        int f = Integer.parseInt(String.valueOf(spinGanancia.getValue()));
        String gan="0.";
        if(f<10){  gan += "0"; }
        gan += String.valueOf(f);
        ganancia = precioCompra* Float.parseFloat(gan);

        precioVenta = precioCompra +ganancia;
        txtPreVenta.setText(String.valueOf(precioVenta));
        lblSugPrecio.setText("Precio Sugerido: $"+String.valueOf(precioVenta));
        lblDiferencia.setText("Diferencia: $"+String.valueOf(ganancia));
    }//GEN-LAST:event_spinGananciaStateChanged

    private void btnSaveModProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveModProdActionPerformed
        String campos = "";
        boolean control = true;
        //Validar y Capturar los Datos y Settearlos en el EntityClass
        if (!txtProdNombre.getText().equals("")){
            aProd.setNombre(txtProdNombre.getText());
        }else{
            campos+= "\n*Nombre de Producto";
            control=false;
        }

        //Validacion para los precios de tipo Floats
        if(!txtPreCompra.getText().equals("0") && !txtPreCompra.getText().equals("")){
            if(txtPreCompra.getText().contains(".")){
                aProd.setPreCompra(Float.parseFloat(txtPreCompra.getText()));
            }else{
                aProd.setPreCompra(Float.parseFloat(txtPreCompra.getText()+".0"));
            }

        }else{
            campos += "\n*Precio de Compra";
            control = false;
        }

        //Setear venta
        if(!txtPreVenta.getText().equals("0") && !txtPreVenta.getText().equals("")){
            if(txtPreVenta.getText().contains(".")){
                aProd.setPreVenta(Float.parseFloat(txtPreVenta.getText()));
            }else{
                aProd.setPreVenta(Float.parseFloat(txtPreVenta.getText()+".0"));
            }

        }else{
            campos += "\n*Precio de Venta";
            control =false;
        }

        if(!txtPrePack.getText().equals("")){
            if(txtPrePack.getText().contains(".")){
                aProd.setPrePack(Float.parseFloat(txtPrePack.getText()));
            }else{
                aProd.setPrePack(Float.parseFloat(txtPrePack.getText()+".00"));
            }
        }

        //Validaion para los Spinner
        if(!spinLocal.getValue().toString().equals("0") && !spinLocal.getValue().toString().equals("")){
            aProd.setLocalCant(Integer.parseInt(spinLocal.getValue().toString()));
        }else{
            campos += "\n*Existencias en Local";
            control = false;
        }

        if(!spinRepos.getValue().toString().equals("0") && !spinRepos.getValue().toString().equals("")){
            aProd.setRepo(Integer.parseInt(spinRepos.getValue().toString()));
        }else{
            campos += "\n*Minimo de Reposición";
            control=false;
        }

        //Settear los Que no necesitan de Validacion.
        aProd.setCantPack(Integer.parseInt(spinPack.getValue().toString()));
        aProd.setMarca(comboMarca.getItemAt(comboMarca.getSelectedIndex()));
        aProd.setPorceGan(Integer.parseInt(spinGanancia.getValue().toString()));
        aProd.setBodegaCant(Integer.parseInt(spinBodega.getValue().toString()));
        boolean r=false;
        String res="";

        if (control){
            try {

                if(insertMode){
                    r=aProd.addProd();
                    res="¡Producto Registrado!";
                }else{
                    r=aProd.modProd();
                    res="¡Producto Modificado!";
                }

                JOptionPane.showMessageDialog(this, res);
                aProd.deselectProd();
                Admin.Administracion frame = new Admin.Administracion();
                frame.setVisible(true);
                this.dispose();

            } catch (SQLException ex) {
                System.out.println("error: "+ex);
                JOptionPane.showMessageDialog(this, "¡No se pudo Realizar la Consulta!...\n Compruebe que los datos que ingresa son correctos");
                Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Ha Olvidado llenar estos Campos Obligatorios:" + campos);
        }
    }//GEN-LAST:event_btnSaveModProdActionPerformed

    private void btnCancelModProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelModProdActionPerformed
        try {
            aProd.deselectProd();
            Admin.Administracion frame = new Admin.Administracion();
            frame.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(AlterAddProd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCancelModProdActionPerformed

    private void txtProvFindKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvFindKeyTyped
         // TODO add your handling code here:
         txtProvFind.addKeyListener(new KeyAdapter() {
        public void keyReleased(final KeyEvent e){
            txtProvFind.setText(txtProvFind.getText());
            repaint();
            filtro.setRowFilter(RowFilter.regexFilter(txtProvFind.getText().trim(),1));
        }
        });
        filtro = new TableRowSorter(this.tablaProvLista.getModel());
        this.tablaProvLista.setRowSorter(filtro);
    }//GEN-LAST:event_txtProvFindKeyTyped

    private void btnProv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProv1ActionPerformed
         // TODO add your handling code here:
         int fila = tablaProvLista.getSelectedRow();
         Image img ;
         
         if(p1){//Si e sverdadero, es porque ya hay un proveedor. por lo tanto, vamo a borrarlo
             aProd.setProv1("0");
             lblProv1.setText("Proveedor 1:");
             p1 = false; //falso porque se elimina,... ya no hay proveedor 
             try {
                 img = ImageIO.read(getClass().getResource("resources/plus2.png"));
                 btnProv1.setIcon(new ImageIcon(img));
             } catch (IOException ex) {
                 Logger.getLogger(AlterAddProd.class.getName()).log(Level.SEVERE, null, ex);
             }
                    
         }else{ //En caso de que no exista un Proveeedor Actualmente
             if(fila>=0){
                 DefaultTableModel model = (DefaultTableModel) tablaProvLista.getModel();
                 String id= model.getValueAt(fila, 0).toString();
                 aProd.setProv1(id);  //setear el id del Proveedor
                 p1=true; //true por que ahora se setea
                 try {
                    lblProv1.setText("Proveedor 1: " + aProd.getProvNombre(Integer.parseInt(id)));
                    img = ImageIO.read(getClass().getResource("resources/plus2.png"));
                    btnProv1.setIcon(new ImageIcon(img));
                 } catch (SQLException ex) {
                     Logger.getLogger(AlterAddProd.class.getName()).log(Level.SEVERE, null, ex);
                 } catch (IOException ex) {
                     Logger.getLogger(AlterAddProd.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }else{
                 JOptionPane.showMessageDialog(this, "Selecione un Proveedor de la lista");
             }
             
         }
         
    }//GEN-LAST:event_btnProv1ActionPerformed

    
    //-------------------------------Campos para -------------------------------------//
    //<editor-fold defaultstate="collapsed" desc="Metodos limpiar, rellenar y validar campos">
    public void limpiarCampos(){
        txtProdNombre.setText("");
        lblCodigo.setText("Codigo: ");
        comboMarca.setSelectedIndex(0);
        txtPreCompra.setText("0");
        txtPreVenta.setText("0");
        spinGanancia.setValue(0);
        lblSugPrecio.setText("Precio Sugerido: $");
        lblDiferencia.setText("Diferencia: $");
        spinPack.setValue(0);
        txtPrePack.setText("0");
        spinLocal.setValue(0); spinBodega.setValue(0); spinRepos.setValue(0);
                
    }
    
    
    
    public void llenarCampos() throws SQLException{     
        
        txtProdNombre.setText(aProd.getNombre());
        lblCodigo.setText("Codigo: "+aProd.getCodigo());
        txtPreCompra.setText(String.valueOf(aProd.getPreCompra()));
        txtPreVenta.setText(String.valueOf(aProd.getPreVenta()));
        spinGanancia.setValue(aProd.getPorceGan());
        spinPack.setValue(aProd.getCantPack());
        txtPrePack.setText(String.valueOf(aProd.getPrePack()));
        spinLocal.setValue(aProd.getLocalCant());
        spinBodega.setValue(aProd.getBodegaCant());
        spinRepos.setValue(aProd.getRepo());
        
        //Para los Label de los Proveedores
        
        if(!aProd.getProv1().equals("-Sin Proveedor-")){
             lblProv1.setText("Proveedor 1: "+aProd.getProv1());
             p1=true;
         }else{
             lblProv1.setText("Proveedor 1: ");
             p1=false;
         }
        
        if(!aProd.getProv2().equals("-Sin Proveedor-")){
             lblProv2.setText("Proveedor 2: "+aProd.getProv2());
             p2=true;
         }else{
             lblProv2.setText("Proveedor 2: ");
             p2=false;
         }
        
        if(!aProd.getProv3().equals("-Sin Proveedor-")){
             lblProv3.setText("Proveedor 3: "+aProd.getProv3());
             p3=true;
             
         }else{
             lblProv3.setText("Proveedor 3: ");
             p3=false;
         }
        
        if(!aProd.getProv4().equals("-Sin Proveedor-")){
             lblProv4.setText("Proveedor 4: "+aProd.getProv4());
             p4=true;
         }else{
             lblProv4.setText("Proovedor 4:");
             p4=false;
         }
        
        
    }//</editor-fold>
    //Validacion para que no se puedan ingresar letras al jTextField
    
    private void validaNum(java.awt.event.KeyEvent evt){
        char val=evt.getKeyChar();
        if (Character.isLetter(val)){
            getToolkit().beep();
            evt.consume();
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterAddProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterAddProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterAddProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterAddProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AlterAddProd().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AlterAddProd.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelModProd;
    private javax.swing.JButton btnProv1;
    private javax.swing.JButton btnProv2;
    private javax.swing.JButton btnProv3;
    private javax.swing.JButton btnProv4;
    private javax.swing.JButton btnSaveModProd;
    public static final javax.swing.JComboBox<String> comboMarca = new javax.swing.JComboBox<>();
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDiferencia;
    private javax.swing.JLabel lblProv1;
    private javax.swing.JLabel lblProv2;
    private javax.swing.JLabel lblProv3;
    private javax.swing.JLabel lblProv4;
    private javax.swing.JLabel lblSugPrecio;
    private javax.swing.JSpinner spinBodega;
    private javax.swing.JSpinner spinGanancia;
    private javax.swing.JSpinner spinLocal;
    private javax.swing.JSpinner spinPack;
    private javax.swing.JSpinner spinRepos;
    public javax.swing.JTable tablaProvLista;
    private javax.swing.JTextField txtPreCompra;
    private javax.swing.JTextField txtPrePack;
    private javax.swing.JTextField txtPreVenta;
    private javax.swing.JTextField txtProdNombre;
    private javax.swing.JTextField txtProvFind;
    // End of variables declaration//GEN-END:variables
}
